set_property SRC_FILE_INFO {cfile:C:/Users/84646/Desktop/integration.srcs/constrs_1/new/debug.xdc rfile:../../../../../../integration.srcs/constrs_1/new/debug.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/84646/Desktop/integration.srcs/constrs_1/imports/constraints/ZYBO_Master.xdc rfile:../../../../../../integration.srcs/constrs_1/imports/constraints/ZYBO_Master.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/84646/Desktop/integration.srcs/constrs_1/imports/constraints/PYNQ-Z1_C.xdc rfile:../../../../../../integration.srcs/constrs_1/imports/constraints/PYNQ-Z1_C.xdc id:3} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name integrated_design_i/OV2AXIS_L/OV_CAM_L/inst/capturer/pclk_out -source [get_ports ov_cam_l_pclk] -divide_by 2 [get_pins integrated_design_i/OV2AXIS_L/OV_CAM_L/inst/capturer/pclk_out_reg/Q]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name integrated_design_i/OV2AXIS_R/OV_CAM_R/inst/capturer/pclk_out -source [get_ports ov_cam_r_pclk] -divide_by 2 [get_pins integrated_design_i/OV2AXIS_R/OV_CAM_R/inst/capturer/pclk_out_reg/Q]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name integrated_design_i/OV2AXIS_L/OV_CAM_L/inst/divider/CLK -source [get_pins {integrated_design_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 250 [get_pins integrated_design_i/OV2AXIS_L/OV_CAM_L/inst/divider/sccbclk_reg/Q]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name integrated_design_i/OV2AXIS_R/OV_CAM_R/inst/divider/CLK -source [get_pins {integrated_design_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -divide_by 250 [get_pins integrated_design_i/OV2AXIS_R/OV_CAM_R/inst/divider/sccbclk_reg/Q]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name integrated_design_i/OV2AXIS_L/OV_CAM_L/inst/sccb/out0 -source [get_pins integrated_design_i/OV2AXIS_L/OV_CAM_L/inst/divider/sccbclk_reg/Q] -divide_by 10 [get_pins {integrated_design_i/OV2AXIS_L/OV_CAM_L/inst/sccb/FSM_onehot_fsm_cs_reg[0]/Q}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name integrated_design_i/OV2AXIS_R/OV_CAM_R/inst/sccb/out0 -source [get_pins integrated_design_i/OV2AXIS_R/OV_CAM_R/inst/divider/sccbclk_reg/Q] -divide_by 10 [get_pins {integrated_design_i/OV2AXIS_R/OV_CAM_R/inst/sccb/FSM_onehot_fsm_cs_reg[0]/Q}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports clk]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.000 -name sys_clk_pin -waveform {0.000 4.000} -add [get_ports clk]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports {sw[0]}]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15 [get_ports {sw[1]}]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13 [get_ports {sw[2]}]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports {sw[3]}]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports {led[0]}]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports {led[1]}]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports {led[2]}]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports {led[3]}]
set_property src_info {type:XDC file:2 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M19 [get_ports {vga_r[0]}]
set_property src_info {type:XDC file:2 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property src_info {type:XDC file:2 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L20 [get_ports {vga_r[1]}]
set_property src_info {type:XDC file:2 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property src_info {type:XDC file:2 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20 [get_ports {vga_r[2]}]
set_property src_info {type:XDC file:2 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property src_info {type:XDC file:2 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G20 [get_ports {vga_r[3]}]
set_property src_info {type:XDC file:2 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
set_property src_info {type:XDC file:2 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F19 [get_ports {vga_r[4]}]
set_property src_info {type:XDC file:2 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[4]}]
set_property src_info {type:XDC file:2 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports {vga_g[0]}]
set_property src_info {type:XDC file:2 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property src_info {type:XDC file:2 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N20 [get_ports {vga_g[1]}]
set_property src_info {type:XDC file:2 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property src_info {type:XDC file:2 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L19 [get_ports {vga_g[2]}]
set_property src_info {type:XDC file:2 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property src_info {type:XDC file:2 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J19 [get_ports {vga_g[3]}]
set_property src_info {type:XDC file:2 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
set_property src_info {type:XDC file:2 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H20 [get_ports {vga_g[4]}]
set_property src_info {type:XDC file:2 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[4]}]
set_property src_info {type:XDC file:2 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports {vga_g[5]}]
set_property src_info {type:XDC file:2 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[5]}]
set_property src_info {type:XDC file:2 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P20 [get_ports {vga_b[0]}]
set_property src_info {type:XDC file:2 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property src_info {type:XDC file:2 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M20 [get_ports {vga_b[1]}]
set_property src_info {type:XDC file:2 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property src_info {type:XDC file:2 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K19 [get_ports {vga_b[2]}]
set_property src_info {type:XDC file:2 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property src_info {type:XDC file:2 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports {vga_b[3]}]
set_property src_info {type:XDC file:2 line:356 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
set_property src_info {type:XDC file:2 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G19 [get_ports {vga_b[4]}]
set_property src_info {type:XDC file:2 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[4]}]
set_property src_info {type:XDC file:2 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P19 [get_ports vga_hs]
set_property src_info {type:XDC file:2 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hs]
set_property src_info {type:XDC file:2 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R19 [get_ports vga_vs]
set_property src_info {type:XDC file:2 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vs]
set_property src_info {type:XDC file:2 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports ov_cam_l_scl_io]
set_property src_info {type:XDC file:2 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports ov_cam_l_sda_io]
set_property src_info {type:XDC file:2 line:380 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports ov_cam_r_scl_io]
set_property src_info {type:XDC file:2 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports ov_cam_r_sda_io]
set_property src_info {type:XDC file:2 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U20 [get_ports {ov_cam_l_d[1]}]
set_property src_info {type:XDC file:2 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W20 [get_ports ov_cam_l_href]
set_property src_info {type:XDC file:2 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V20 [get_ports {ov_cam_l_d[4]}]
set_property src_info {type:XDC file:2 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y19 [get_ports {ov_cam_l_d[5]}]
set_property src_info {type:XDC file:2 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports ov_cam_l_xclk]
set_property src_info {type:XDC file:2 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W18 [get_ports {ov_cam_l_d[0]}]
set_property src_info {type:XDC file:2 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T20 [get_ports ov_cam_l_pwdn]
set_property src_info {type:XDC file:2 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports ov_cam_l_resetn]
set_property src_info {type:XDC file:2 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W15 [get_ports {ov_cam_l_d[2]}]
set_property src_info {type:XDC file:2 line:482 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V15 [get_ports {ov_cam_l_d[6]}]
set_property src_info {type:XDC file:2 line:486 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T10 [get_ports ov_cam_l_sda_io]
set_property src_info {type:XDC file:2 line:487 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ov_cam_l_sda_io]
set_property src_info {type:XDC file:2 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T11 [get_ports ov_cam_l_vsync]
set_property src_info {type:XDC file:2 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y14 [get_ports {ov_cam_l_d[3]}]
set_property src_info {type:XDC file:2 line:498 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W14 [get_ports {ov_cam_l_d[7]}]
set_property src_info {type:XDC file:2 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U12 [get_ports ov_cam_l_scl_io]
set_property src_info {type:XDC file:2 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ov_cam_l_scl_io]
set_property src_info {type:XDC file:2 line:506 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T12 [get_ports ov_cam_l_pclk]
set_property src_info {type:XDC file:2 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ov_cam_l_pclk_IBUF]
set_property src_info {type:XDC file:2 line:510 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ov_cam_l_pclk_IBUF_BUFG]
set_property src_info {type:XDC file:2 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T15 [get_ports {ov_cam_r_d[1]}]
set_property src_info {type:XDC file:2 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T14 [get_ports ov_cam_r_pwdn]
set_property src_info {type:XDC file:2 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports ov_cam_r_href]
set_property src_info {type:XDC file:2 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P14 [get_ports {ov_cam_r_d[4]}]
set_property src_info {type:XDC file:2 line:531 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U15 [get_ports {ov_cam_r_d[5]}]
set_property src_info {type:XDC file:2 line:535 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U14 [get_ports ov_cam_r_resetn]
set_property src_info {type:XDC file:2 line:539 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V18 [get_ports ov_cam_r_xclk]
set_property src_info {type:XDC file:2 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {ov_cam_r_d[0]}]
set_property src_info {type:XDC file:2 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports {ov_cam_r_d[6]}]
set_property src_info {type:XDC file:2 line:552 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports {ov_cam_r_d[2]}]
set_property src_info {type:XDC file:2 line:556 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports ov_cam_r_vsync]
set_property src_info {type:XDC file:2 line:560 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports ov_cam_r_sda_io]
set_property src_info {type:XDC file:2 line:561 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ov_cam_r_sda_io]
set_property src_info {type:XDC file:2 line:564 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V13 [get_ports {ov_cam_r_d[7]}]
set_property src_info {type:XDC file:2 line:568 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U17 [get_ports {ov_cam_r_d[3]}]
set_property src_info {type:XDC file:2 line:572 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports ov_cam_r_pclk]
set_property src_info {type:XDC file:2 line:576 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y17 [get_ports ov_cam_r_scl_io]
set_property src_info {type:XDC file:2 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports ov_cam_r_scl_io]
set_property src_info {type:XDC file:2 line:579 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ov_cam_r_pclk_IBUF]
set_property src_info {type:XDC file:2 line:580 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ov_cam_r_pclk_IBUF_BUFG]
set_property src_info {type:XDC file:3 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports {sw[0]}]
set_property src_info {type:XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS33} [get_ports {sw[1]}]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
set_property src_info {type:XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports {led[2]}]
set_property src_info {type:XDC file:3 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports {led[3]}]
set_property src_info {type:XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports ov_cam_l_scl_io]
set_property src_info {type:XDC file:3 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports ov_cam_l_sda_io]
set_property src_info {type:XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports ov_cam_r_scl_io]
set_property src_info {type:XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports ov_cam_r_sda_io]
set_property src_info {type:XDC file:3 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ov_cam_l_pclk_IBUF]
set_property src_info {type:XDC file:3 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ov_cam_l_pclk_IBUF_BUFG]
set_property src_info {type:XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ov_cam_r_pclk_IBUF]
set_property src_info {type:XDC file:3 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ov_cam_r_pclk_IBUF_BUFG]
set_property src_info {type:XDC file:3 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports ov_cam_l_pwdn]
set_property src_info {type:XDC file:3 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports {ov_cam_l_d[1]}]
set_property src_info {type:XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {ov_cam_l_d[4]}]
set_property src_info {type:XDC file:3 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVCMOS33} [get_ports ov_cam_l_href]
set_property src_info {type:XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports {ov_cam_l_d[6]}]
set_property src_info {type:XDC file:3 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {ov_cam_l_d[2]}]
set_property src_info {type:XDC file:3 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports ov_cam_l_vsync]
set_property src_info {type:XDC file:3 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports ov_cam_l_sda_io]
set_property src_info {type:XDC file:3 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports ov_cam_r_resetn]
set_property src_info {type:XDC file:3 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports {ov_cam_r_d[5]}]
set_property src_info {type:XDC file:3 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports {ov_cam_r_d[0]}]
set_property src_info {type:XDC file:3 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports ov_cam_r_xclk]
set_property src_info {type:XDC file:3 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports {ov_cam_r_d[7]}]
set_property src_info {type:XDC file:3 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {ov_cam_r_d[3]}]
set_property src_info {type:XDC file:3 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVCMOS33} [get_ports ov_cam_l_resetn]
set_property src_info {type:XDC file:3 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVCMOS33} [get_ports {ov_cam_l_d[5]}]
set_property src_info {type:XDC file:3 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V6 IOSTANDARD LVCMOS33} [get_ports {ov_cam_l_d[0]}]
set_property src_info {type:XDC file:3 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports ov_cam_l_xclk]
set_property src_info {type:XDC file:3 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V7 IOSTANDARD LVCMOS33} [get_ports {ov_cam_l_d[7]}]
set_property src_info {type:XDC file:3 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U8 IOSTANDARD LVCMOS33} [get_ports {ov_cam_l_d[3]}]
set_property src_info {type:XDC file:3 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V8 IOSTANDARD LVCMOS33} [get_ports ov_cam_l_pclk]
set_property src_info {type:XDC file:3 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVCMOS33} [get_ports ov_cam_l_scl_io]
set_property src_info {type:XDC file:3 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W10 IOSTANDARD LVCMOS33} [get_ports ov_cam_r_pwdn]
set_property src_info {type:XDC file:3 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y6 IOSTANDARD LVCMOS33} [get_ports {ov_cam_r_d[1]}]
set_property src_info {type:XDC file:3 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y7 IOSTANDARD LVCMOS33} [get_ports {ov_cam_r_d[4]}]
set_property src_info {type:XDC file:3 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W8 IOSTANDARD LVCMOS33} [get_ports ov_cam_r_href]
set_property src_info {type:XDC file:3 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y8 IOSTANDARD LVCMOS33} [get_ports {ov_cam_r_d[6]}]
set_property src_info {type:XDC file:3 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W9 IOSTANDARD LVCMOS33} [get_ports {ov_cam_r_d[2]}]
set_property src_info {type:XDC file:3 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y9 IOSTANDARD LVCMOS33} [get_ports ov_cam_r_vsync]
set_property src_info {type:XDC file:3 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y13 IOSTANDARD LVCMOS33} [get_ports ov_cam_r_pclk]
set_property src_info {type:XDC file:3 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports ov_cam_r_scl_io]
set_property src_info {type:XDC file:3 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports ov_cam_r_sda_io]
set_property src_info {type:XDC file:3 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD TMDS_33} [get_ports hdmi_out_clk_n]
set_property src_info {type:XDC file:3 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD TMDS_33} [get_ports hdmi_out_clk_p]
set_property src_info {type:XDC file:3 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD TMDS_33} [get_ports {hdmi_out_data_n[0]}]
set_property src_info {type:XDC file:3 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD TMDS_33} [get_ports {hdmi_out_data_p[0]}]
set_property src_info {type:XDC file:3 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD TMDS_33} [get_ports {hdmi_out_data_n[1]}]
set_property src_info {type:XDC file:3 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD TMDS_33} [get_ports {hdmi_out_data_p[1]}]
set_property src_info {type:XDC file:3 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD TMDS_33} [get_ports {hdmi_out_data_n[2]}]
set_property src_info {type:XDC file:3 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD TMDS_33} [get_ports {hdmi_out_data_p[2]}]
