# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/84646/Desktop/Pmode/pmod_3/Pmod_30M_1/Pmod_30M.srcs/sources_1/ip/PLL_108_1/PLL_108.xci
# IP: The module: 'PLL_108' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/84646/Desktop/Pmode/pmod_3/Pmod_30M_1/Pmod_30M.srcs/sources_1/ip/PLL_108_1/PLL_108_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_108'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/84646/Desktop/Pmode/pmod_3/Pmod_30M_1/Pmod_30M.srcs/sources_1/ip/PLL_108_1/PLL_108.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_108'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/84646/Desktop/Pmode/pmod_3/Pmod_30M_1/Pmod_30M.srcs/sources_1/ip/PLL_108_1/PLL_108_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_108'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/84646/Desktop/Pmode/pmod_3/Pmod_30M_1/Pmod_30M.srcs/sources_1/ip/PLL_108_1/PLL_108.xci
# IP: The module: 'PLL_108' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/84646/Desktop/Pmode/pmod_3/Pmod_30M_1/Pmod_30M.srcs/sources_1/ip/PLL_108_1/PLL_108_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_108'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/84646/Desktop/Pmode/pmod_3/Pmod_30M_1/Pmod_30M.srcs/sources_1/ip/PLL_108_1/PLL_108.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_108'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/84646/Desktop/Pmode/pmod_3/Pmod_30M_1/Pmod_30M.srcs/sources_1/ip/PLL_108_1/PLL_108_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_108'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
