# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/84646/Desktop/integration.srcs/constrs_1/new/debug.xdc

# XDC: C:/Users/84646/Desktop/integration.srcs/constrs_1/imports/constraints/ZYBO_Master.xdc

# XDC: C:/Users/84646/Desktop/integration.srcs/constrs_1/imports/constraints/PYNQ-Z1_C.xdc

# Block Designs: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/integrated_design.bd
# Block Designs: The module: 'integrated_design' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_OV_CAM_0_0/integrated_design_OV_CAM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_OV_CAM_0_0 || ORIG_REF_NAME==integrated_design_OV_CAM_0_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_xlconstant_0_0/integrated_design_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_xlconstant_0_0 || ORIG_REF_NAME==integrated_design_xlconstant_0_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_v_vid_in_axi4s_0_0/integrated_design_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==integrated_design_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_clk_wiz_0_0/integrated_design_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_clk_wiz_0_0 || ORIG_REF_NAME==integrated_design_clk_wiz_0_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_xlconcat_0_0/integrated_design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_xlconcat_0_0 || ORIG_REF_NAME==integrated_design_xlconcat_0_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_processing_system7_0_0/integrated_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_processing_system7_0_0 || ORIG_REF_NAME==integrated_design_processing_system7_0_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_0_0/integrated_design_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_axi_vdma_0_0 || ORIG_REF_NAME==integrated_design_axi_vdma_0_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_ps7_0_axi_periph_0/integrated_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==integrated_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_rst_ps7_0_100M_0/integrated_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==integrated_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_mem_intercon_0/integrated_design_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_axi_mem_intercon_0 || ORIG_REF_NAME==integrated_design_axi_mem_intercon_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_rst_ps7_0_150M_0/integrated_design_rst_ps7_0_150M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_rst_ps7_0_150M_0 || ORIG_REF_NAME==integrated_design_rst_ps7_0_150M_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_v_tc_0_0/integrated_design_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_v_tc_0_0 || ORIG_REF_NAME==integrated_design_v_tc_0_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_v_axi4s_vid_out_0_0/integrated_design_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==integrated_design_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_xlconstant_1_0/integrated_design_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_xlconstant_1_0 || ORIG_REF_NAME==integrated_design_xlconstant_1_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_OV_CAM_L_0/integrated_design_OV_CAM_L_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_OV_CAM_L_0 || ORIG_REF_NAME==integrated_design_OV_CAM_L_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_v_vid_in_axi4s_0_1/integrated_design_v_vid_in_axi4s_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_v_vid_in_axi4s_0_1 || ORIG_REF_NAME==integrated_design_v_vid_in_axi4s_0_1} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_0_1/integrated_design_axi_vdma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_axi_vdma_0_1 || ORIG_REF_NAME==integrated_design_axi_vdma_0_1} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_xlconcat_1_0/integrated_design_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_xlconcat_1_0 || ORIG_REF_NAME==integrated_design_xlconcat_1_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_preprocess_0_0/integrated_design_preprocess_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_preprocess_0_0 || ORIG_REF_NAME==integrated_design_preprocess_0_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_2_0/integrated_design_axi_vdma_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_axi_vdma_2_0 || ORIG_REF_NAME==integrated_design_axi_vdma_2_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_2_1/integrated_design_axi_vdma_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_axi_vdma_2_1 || ORIG_REF_NAME==integrated_design_axi_vdma_2_1} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_preprocess_0_1/integrated_design_preprocess_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_preprocess_0_1 || ORIG_REF_NAME==integrated_design_preprocess_0_1} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_mem_intercon_1_1/integrated_design_axi_mem_intercon_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_axi_mem_intercon_1_1 || ORIG_REF_NAME==integrated_design_axi_mem_intercon_1_1} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_mem_intercon_2_0/integrated_design_axi_mem_intercon_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_axi_mem_intercon_2_0 || ORIG_REF_NAME==integrated_design_axi_mem_intercon_2_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_2_2/integrated_design_axi_vdma_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_axi_vdma_2_2 || ORIG_REF_NAME==integrated_design_axi_vdma_2_2} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_3_0/integrated_design_axi_vdma_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_axi_vdma_3_0 || ORIG_REF_NAME==integrated_design_axi_vdma_3_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_mem_intercon_3_0/integrated_design_axi_mem_intercon_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_axi_mem_intercon_3_0 || ORIG_REF_NAME==integrated_design_axi_mem_intercon_3_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_rgb2dvi_0_0/integrated_design_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_rgb2dvi_0_0 || ORIG_REF_NAME==integrated_design_rgb2dvi_0_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_xbar_0/integrated_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_xbar_0 || ORIG_REF_NAME==integrated_design_xbar_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_xbar_2/integrated_design_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_xbar_2 || ORIG_REF_NAME==integrated_design_xbar_2} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_xbar_3/integrated_design_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_xbar_3 || ORIG_REF_NAME==integrated_design_xbar_3} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_xbar_1/integrated_design_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_xbar_1 || ORIG_REF_NAME==integrated_design_xbar_1} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_stereo_0_0/integrated_design_stereo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_stereo_0_0 || ORIG_REF_NAME==integrated_design_stereo_0_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axis_broadcaster_0_0/integrated_design_axis_broadcaster_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_axis_broadcaster_0_0 || ORIG_REF_NAME==integrated_design_axis_broadcaster_0_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axis_broadcaster_1_0/integrated_design_axis_broadcaster_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_axis_broadcaster_1_0 || ORIG_REF_NAME==integrated_design_axis_broadcaster_1_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_1_0/integrated_design_axi_vdma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_axi_vdma_1_0 || ORIG_REF_NAME==integrated_design_axi_vdma_1_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_xbar_4/integrated_design_xbar_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_xbar_4 || ORIG_REF_NAME==integrated_design_xbar_4} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_auto_pc_0/integrated_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_auto_pc_0 || ORIG_REF_NAME==integrated_design_auto_pc_0} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_auto_pc_1/integrated_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_auto_pc_1 || ORIG_REF_NAME==integrated_design_auto_pc_1} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_auto_pc_2/integrated_design_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_auto_pc_2 || ORIG_REF_NAME==integrated_design_auto_pc_2} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_auto_pc_3/integrated_design_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_auto_pc_3 || ORIG_REF_NAME==integrated_design_auto_pc_3} -quiet] -quiet

# IP: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_auto_pc_4/integrated_design_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==integrated_design_auto_pc_4 || ORIG_REF_NAME==integrated_design_auto_pc_4} -quiet] -quiet

# XDC: C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/integrated_design_ooc.xdc
