# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/84646/Desktop/Ne/double_camera/2_cam/2_cam.cache/wt [current_project]
set_property parent.project_path C:/Users/84646/Desktop/Ne/double_camera/2_cam/2_cam.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/84646/Desktop/Ne/double_camera/2_cam/2_cam.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/integrated_design.bd
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_v_vid_in_axi4s_0_0/integrated_design_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_v_vid_in_axi4s_0_0/integrated_design_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_clk_wiz_0_0/integrated_design_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_clk_wiz_0_0/integrated_design_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_clk_wiz_0_0/integrated_design_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_processing_system7_0_0/integrated_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_0_0/integrated_design_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_0_0/integrated_design_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_0_0/integrated_design_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_rst_ps7_0_100M_0/integrated_design_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_rst_ps7_0_100M_0/integrated_design_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_rst_ps7_0_100M_0/integrated_design_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_rst_ps7_0_150M_0/integrated_design_rst_ps7_0_150M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_rst_ps7_0_150M_0/integrated_design_rst_ps7_0_150M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_rst_ps7_0_150M_0/integrated_design_rst_ps7_0_150M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_v_tc_0_0/integrated_design_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_v_tc_0_0/integrated_design_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_v_axi4s_vid_out_0_0/integrated_design_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_v_axi4s_vid_out_0_0/integrated_design_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_v_vid_in_axi4s_0_1/integrated_design_v_vid_in_axi4s_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_v_vid_in_axi4s_0_1/integrated_design_v_vid_in_axi4s_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_0_1/integrated_design_axi_vdma_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_0_1/integrated_design_axi_vdma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_0_1/integrated_design_axi_vdma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_preprocess_0_0/constraints/preprocess_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_2_0/integrated_design_axi_vdma_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_2_0/integrated_design_axi_vdma_2_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_2_0/integrated_design_axi_vdma_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_2_1/integrated_design_axi_vdma_2_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_2_1/integrated_design_axi_vdma_2_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_2_1/integrated_design_axi_vdma_2_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_preprocess_0_1/constraints/preprocess_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_2_2/integrated_design_axi_vdma_2_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_2_2/integrated_design_axi_vdma_2_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_2_2/integrated_design_axi_vdma_2_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_3_0/integrated_design_axi_vdma_3_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_3_0/integrated_design_axi_vdma_3_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_3_0/integrated_design_axi_vdma_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_xbar_0/integrated_design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_xbar_2/integrated_design_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_xbar_3/integrated_design_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_xbar_1/integrated_design_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_stereo_0_0/constraints/stereo_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axis_broadcaster_0_0/integrated_design_axis_broadcaster_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axis_broadcaster_1_0/integrated_design_axis_broadcaster_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_1_0/integrated_design_axi_vdma_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_1_0/integrated_design_axi_vdma_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_axi_vdma_1_0/integrated_design_axi_vdma_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_xbar_4/integrated_design_xbar_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_auto_pc_0/integrated_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_auto_pc_1/integrated_design_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_auto_pc_2/integrated_design_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_auto_pc_3/integrated_design_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/ip/integrated_design_auto_pc_4/integrated_design_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/84646/Desktop/integration.srcs/sources_1/bd/integrated_design/integrated_design_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/84646/Desktop/integration.srcs/constrs_1/new/debug.xdc
set_property used_in_implementation false [get_files C:/Users/84646/Desktop/integration.srcs/constrs_1/new/debug.xdc]

read_xdc C:/Users/84646/Desktop/integration.srcs/constrs_1/imports/constraints/ZYBO_Master.xdc
set_property used_in_implementation false [get_files C:/Users/84646/Desktop/integration.srcs/constrs_1/imports/constraints/ZYBO_Master.xdc]

read_xdc C:/Users/84646/Desktop/integration.srcs/constrs_1/imports/constraints/PYNQ-Z1_C.xdc
set_property used_in_implementation false [get_files C:/Users/84646/Desktop/integration.srcs/constrs_1/imports/constraints/PYNQ-Z1_C.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top integrated_design -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef integrated_design.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file integrated_design_utilization_synth.rpt -pb integrated_design_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
