#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.1 (64-bit)
#
# Filename    : integrated_design.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Aug 12 12:23:50 +0800 2019
# SW Build 2188600 on Wed Apr  4 18:40:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: integrated_design.sh [-help]
# usage: integrated_design.sh [-lib_map_path]
# usage: integrated_design.sh [-noclean_files]
# usage: integrated_design.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'integrated_design.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm fifo_generator_v13_1_2 v_vid_in_axi4s_v4_0_4 processing_system7_bfm_v2_0_5 lib_cdc_v1_0_2 lib_pkg_v1_0_2 lib_fifo_v1_0_6 blk_mem_gen_v8_3_4 lib_bmg_v1_0_6 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_12 axi_vdma_v6_2_9 proc_sys_reset_v5_0_10 axi_lite_ipif_v3_0_4 v_tc_v6_1_9 v_axi4s_vid_out_v4_0_4 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_10 axi_data_fifo_v2_1_9 axi_crossbar_v2_1_11 axis_infrastructure_v1_1_0 axis_broadcaster_v1_1_10 axi_protocol_converter_v2_1_10)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "integrated_design.sh - Script generated by export_simulation (Vivado v2018.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "C:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2018.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../bd/integrated_design/ipshared/42fb/OV_CAM.srcs/sources_1/new/OV5640_Config.v" \
    "$ref_dir/../../../bd/integrated_design/ipshared/42fb/OV_CAM.srcs/sources_1/new/OV7670_Config.v" \
    "$ref_dir/../../../bd/integrated_design/ipshared/42fb/OV_CAM.srcs/sources_1/imports/zybo_stereo/OV_CAM_SCCB.v" \
    "$ref_dir/../../../bd/integrated_design/ipshared/42fb/OV_CAM.srcs/sources_1/imports/zybo_stereo/OV_CAM_Controller.v" \
    "$ref_dir/../../../bd/integrated_design/ipshared/42fb/OV_CAM.srcs/sources_1/imports/zybo_stereo/OV_CAM_Capture.v" \
    "$ref_dir/../../../bd/integrated_design/ipshared/42fb/OV_CAM.srcs/sources_1/imports/zybo_stereo/OV_CAM_CLK_Divider.v" \
    "$ref_dir/../../../bd/integrated_design/ipshared/42fb/OV_CAM.srcs/sources_1/imports/zybo_stereo/OV_CAM.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_OV_CAM_0_0/sim/integrated_design_OV_CAM_0_0.v" \
    "$ref_dir/../../../bd/integrated_design/ipshared/e147/xlconstant.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_xlconstant_0_0/sim/integrated_design_xlconstant_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_1_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/a807/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_1_2 $vhdlan_opts \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/a807/hdl/fifo_generator_v13_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/a807/hdl/fifo_generator_v13_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_vid_in_axi4s_v4_0_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/251f/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_v_vid_in_axi4s_0_0/sim/integrated_design_v_vid_in_axi4s_0_0.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_clk_wiz_0_0/integrated_design_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_clk_wiz_0_0/integrated_design_clk_wiz_0_0.v" \
    "$ref_dir/../../../bd/integrated_design/ipshared/2e37/xlconcat.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_xlconcat_0_0/sim/integrated_design_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_bfm_v2_0_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl/processing_system7_bfm_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_processing_system7_0_0/sim/integrated_design_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/832a/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_6 $vhdlan_opts \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/61a7/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_3_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/59b0/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_6 $vhdlan_opts \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7d44/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/6039/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_12 $vhdlan_opts \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1cd0/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_2_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl/axi_vdma_v6_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_2_9 $vhdlan_opts \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl/axi_vdma_v6_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_axi_vdma_0_0/sim/integrated_design_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_10 $vhdlan_opts \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/04b4/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_rst_ps7_0_100M_0/sim/integrated_design_rst_ps7_0_100M_0.vhd" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_rst_ps7_0_150M_0/sim/integrated_design_rst_ps7_0_150M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/0ba0/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_9 $vhdlan_opts \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/9581/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_v_tc_0_0/sim/integrated_design_v_tc_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_axi4s_vid_out_v4_0_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/a7c9/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_v_axi4s_vid_out_0_0/sim/integrated_design_v_axi4s_vid_out_0_0.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_xlconstant_1_0/sim/integrated_design_xlconstant_1_0.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_OV_CAM_L_0/sim/integrated_design_OV_CAM_L_0.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_v_vid_in_axi4s_0_1/sim/integrated_design_v_vid_in_axi4s_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_axi_vdma_0_1/sim/integrated_design_axi_vdma_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_xlconcat_1_0/sim/integrated_design_xlconcat_1_0.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/preprocess_map2_dpcA.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/Block_proc.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/start_for_Mat2AXItde.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/Remap.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/Remap_nearest_bufbkb.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/preprocess.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/preprocess_img_rafYi.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/preprocess_urem_1eOg.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/AXIvideo2Mat_1.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/preprocess_img_raibs.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/preprocess_map1_dmb6.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/preprocess_img_rajbC.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/preprocess_img_dsqcK.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/start_for_Remap_U0.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/preprocess_img_dssc4.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/preprocess_map1_dncg.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/AXIvideo2Mat.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/preprocess_map2_docq.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/Remap_nearest.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/preprocess_img_rakbM.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/preprocess_img_dsrcU.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/Mat2AXIvideo.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/Remap_nearest_r.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/preprocess_img_rahbi.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/preprocess_img_rag8j.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/AXIvideo2Mat48.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/33a8/hdl/verilog/preprocess_img_ralbW.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_preprocess_0_0/sim/integrated_design_preprocess_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_axi_vdma_2_0/sim/integrated_design_axi_vdma_2_0.vhd" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_axi_vdma_2_1/sim/integrated_design_axi_vdma_2_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_preprocess_0_1/sim/integrated_design_preprocess_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_axi_vdma_2_2/sim/integrated_design_axi_vdma_2_2.vhd" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_axi_vdma_3_0/sim/integrated_design_axi_vdma_3_0.vhd" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/dc1a/src/ClockGen.vhd" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/dc1a/src/SyncAsync.vhd" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/dc1a/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/dc1a/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/dc1a/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/dc1a/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/dc1a/src/rgb2dvi.vhd" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_rgb2dvi_0_0/sim/integrated_design_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7ee0/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7efe/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/10b8/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/d552/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_xbar_0/sim/integrated_design_xbar_0.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_xbar_2/sim/integrated_design_xbar_2.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_xbar_3/sim/integrated_design_xbar_3.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_xbar_1/sim/integrated_design_xbar_1.v" \
    "$ref_dir/../../../bd/integrated_design/hdl/integrated_design.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereoBM_minSAD.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereo_img_src_r_bnm.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereo_img_src_l_bjl.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereoBM.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/Block_proc.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereo_img_src_l_bhl.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereo_img_src_l_bkl.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereo.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/start_for_stereoBbtn.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereoBM_index.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereo_img_src_r_bom.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereoBM_buf_l_vabkb.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereo_img_src_l_bil.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereo_img_src_r_bml.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/start_for_CvtColobun.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereo_img_src_l_bfk.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereo_img_dst_dabrm.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/AXIvideo2Mat.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereo_img_src_l_bgk.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereoBM_buf_l_vaeOg.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereo_img_dst_dabqm.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereo_img_dst_dabsm.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/start_for_Mat2AXIbvn.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/AXIvideo2Mat46.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereo_img_src_l_bll.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/Mat2AXIvideo.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/SAD.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/stereo_img_disp_dbpm.v" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/1f73/hdl/verilog/CvtColor.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_stereo_0_0/sim/integrated_design_stereo_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_axis_broadcaster_0_0/hdl/tdata_integrated_design_axis_broadcaster_0_0.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_axis_broadcaster_0_0/hdl/tuser_integrated_design_axis_broadcaster_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_broadcaster_v1_1_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/9136/hdl/axis_broadcaster_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_axis_broadcaster_0_0/hdl/top_integrated_design_axis_broadcaster_0_0.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_axis_broadcaster_0_0/sim/integrated_design_axis_broadcaster_0_0.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_axis_broadcaster_1_0/hdl/tdata_integrated_design_axis_broadcaster_1_0.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_axis_broadcaster_1_0/hdl/tuser_integrated_design_axis_broadcaster_1_0.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_axis_broadcaster_1_0/hdl/top_integrated_design_axis_broadcaster_1_0.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_axis_broadcaster_1_0/sim/integrated_design_axis_broadcaster_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_axi_vdma_1_0/sim/integrated_design_axi_vdma_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_xbar_4/sim/integrated_design_xbar_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/4a8b/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/db52" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/2527/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/3e37/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../../../../integration.srcs/sources_1/bd/integrated_design/ipshared/fe67/hdl" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_auto_pc_0/sim/integrated_design_auto_pc_0.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_auto_pc_1/sim/integrated_design_auto_pc_1.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_auto_pc_2/sim/integrated_design_auto_pc_2.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_auto_pc_3/sim/integrated_design_auto_pc_3.v" \
    "$ref_dir/../../../bd/integrated_design/ip/integrated_design_auto_pc_4/sim/integrated_design_auto_pc_4.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.integrated_design xil_defaultlib.glbl -o integrated_design_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./integrated_design_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./integrated_design.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key integrated_design_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc integrated_design_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./integrated_design.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: integrated_design.sh [-help]\n\
Usage: integrated_design.sh [-lib_map_path]\n\
Usage: integrated_design.sh [-reset_run]\n\
Usage: integrated_design.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
